version: '3.4'

services:
  vizbackend:
      build:
        context: ./nbaviz  # Path to the backend Dockerfile
      container_name: vizbackend
      ports:
        - "8000:8000"  # Expose backend port (adjust as needed)
      environment:
        - DJANGO_SETTINGS_MODULE=nbaviz.settings
        - NODE_ENV=production
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      depends_on:
        - vizdb  # Example if there's a database service
      volumes:
        - ./nbaviz:/app  # Mount the backend directory
        - /app/node_modules  # Avoid mounting node_modules from host
      networks:
        - app-network

  vizdb:
    image: postgres:latest  # Example database service
    container_name: vizdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
